### ISSUE TITLE
账号密码错误，确定账号没有错误

### ISSUE THREAD

**Issue by xx668888** [ZainCheung/netease-cloud-api#1]

**Comment by xx668888** [comment]
![image](https://user-images.githubusercontent.com/41692185/85978511-764a1b80-ba11-11ea-95c3-0a302b174f4a.png)
咋回事

**Comment by ZainCheung** [comment]
我这边进你的api就是正常状态，清除浏览器缓存和cookie你再试试
![image](https://user-images.githubusercontent.com/49631199/85980270-a5ae5780-ba14-11ea-980e-4d63050eb4fd.png)

**Comment by qq517351411** [comment]
我登录不成功 你能登录成功吗？

**Comment by xx668888** [comment]
> 我这边进你的api就是正常状态，清除浏览器缓存和cookie你再试试
> ![image](https://user-images.githubusercontent.com/49631199/85980270-a5ae5780-ba14-11ea-980e-4d63050eb4fd.png)

我登录不成功 你能登录成功吗？

**Comment by ZainCheung** [comment]
登陆也是可以的
![image](https://user-images.githubusercontent.com/49631199/85980822-b0b5b780-ba15-11ea-9915-bb1308494081.png)

**Comment by qq517351411** [comment]
> 登陆也是可以的
> ![image](https://user-images.githubusercontent.com/49631199/85980822-b0b5b780-ba15-11ea-9915-bb1308494081.png)

有群什么的吗？我这里登录上去 提示密码错误，神奇啊，我在别的网站都可以登录

**Comment by xx668888** [comment]
> 登陆也是可以的
> ![image](https://user-images.githubusercontent.com/49631199/85980822-b0b5b780-ba15-11ea-9915-bb1308494081.png)

![image](https://user-images.githubusercontent.com/41692185/85981227-6bde5080-ba16-11ea-8e5d-fce80a26a895.png)
手机号 登录 密码错误  有联系方式什么的么

**Comment by ZainCheung** [comment]
你那个密码错了，，要用MD5，不可以直接传明文密码,请看文档说明

**Comment by xx668888** [comment]
> 你那个密码错了，，要用MD5，不可以直接传明文密码,请看文档说明

可以了，谢谢大哥

**Comment by xx668888** [comment]
大哥 这个接口支持并发吗？ 同时刷好几个号的  可以吗

**Comment by ZainCheung** [comment]
并发场景我没试过，如果你的服务器撑得住你可以试试
