### ISSUE TITLE
腾讯云云函数无法使用glitch.com上搭建的API

### ISSUE THREAD

**Issue by Tokisaki-Galaxy** [ZainCheung/netease-cloud-api#13]
腾讯云的云函数无法使用https://netease-cloud-api.glitch.me/这个地址，显示api测试异常，日志里显示HTTP返回码是503。
我尝试自己在glitch.com上搭建，但仍然无法在腾讯云上使用，尝试在自己的电脑上运行，可以使用。
话说你们有相似经历吗。

**Comment by ZainCheung** [comment]
自行搭建API后要修改配置文件的API地址，本地和云函数确保一致的话是不会存在这种不确定差异的。

**Comment by Tokisaki-Galaxy** [comment]
确定是地址是一样的，问题是偶尔出现，我猜大概是腾讯云的锅吧。。
