### ISSUE TITLE
网址失效了大佬

### ISSUE THREAD

**Issue by 691195086** [ZainCheung/netease-cloud-api#15]
https://netease-cloud-api.glitch.me/，加载不进去了，希望大佬有时间看一看，谢谢

**Comment by ZainCheung** [comment]
因为用的人多，大家自己动手搭建一个吧，看教程两分钟就能搭好

**Comment by sandglasstu** [comment]
> 因为用的人多，大家自己动手搭建一个吧，看教程两分钟就能搭好

大佬 现在自己搭建的貌似也失效了，数据获取的不对，而且一天也没新增几首

**Comment by ZainCheung** [comment]
> > 因为用的人多，大家自己动手搭建一个吧，看教程两分钟就能搭好
> 
> 大佬 现在自己搭建的貌似也失效了，数据获取的不对，而且一天也没新增几首

建议更新一下API，然后使用这个项目：
https://github.com/ZainCheung/netease-cloud-fastplay
更改一下自己的听歌风格，因为每天刷的300首是来自于你的每日推荐歌单，当听歌偏好一直没有变化的时候，网易云推送系统陷入了死循环，推来推去就那些歌，而这些恰好你都听过了，累计播放自然就不会上涨了。
