### ISSUE TITLE
部署报错:Could not load Google Recaptcha. To remix a project, please disable any extensions that might block Google Recaptcha and try again.

### ISSUE THREAD

**Issue by 1287469408** [ZainCheung/netease-cloud-api#17]
失效

**Comment by ZainCheung** [comment]
请看下前面的issue

**Comment by 1287469408** [comment]
大佬显示这个怎么解决Could not load Google Recaptcha. To remix a project, please disable any extensions that might block Google Recaptcha and try again.

**Comment by ZainCheung** [comment]
无法加载Google Recaptcha。要重新组合一个项目，请禁用任何可能阻止Google Recaptcha的扩展，然后再试一次
你复制项目的时候出的问题，谷歌人机验证加载不出来，等网络环境好点再试试吧
