### ISSUE TITLE
接口似乎失效

### ISSUE THREAD

**Issue by ZPLSSSTD** [ZainCheung/netease-cloud-api#18]
你好，我把API部署到我自己的服务器上，按照你说的访问也可以跳出help.html页面。然后点击页面中的检查它返回{code:301}。接着这两天Server酱都提示听歌任务完成，可是我去网易看了一下记录，并没有变化。两天没有增加1首歌。请问这是api的问题还是？

**Comment by ZainCheung** [comment]
> 你好，我把API部署到我自己的服务器上，按照你说的访问也可以跳出help.html页面。然后点击页面中的检查它返回{code:301}。接着这两天Server酱都提示听歌任务完成，可是我去网易看了一下记录，并没有变化。两天没有增加1首歌。请问这是api的问题还是？

建议更新一下API，然后使用这个项目：
https://github.com/ZainCheung/netease-cloud-fastplay
更改一下自己的听歌风格，因为每天刷的300首是来自于你的每日推荐歌单，当听歌偏好一直没有变化的时候，网易云推送系统陷入了死循环，推来推去就那些歌，而这些恰好你都听过了，累计播放自然就不会上涨了。
