### ISSUE TITLE
【活动】API接口征集

### ISSUE THREAD

**Issue by ZainCheung** [ZainCheung/netease-cloud-api#31]
### 格式要求：
接口地址：填写你的API地址，要求打开后可以看到欢迎界面

**Comment by jdkide** [comment]
业余小白想请教一下，如果我想把这个项目改成用于刷某个歌单的播放量而不是单曲的播放量该从何入手呢？也是一样的技术原理吗？不是很懂，希望这个问题没有太白痴哈哈。

**Comment by BoyceLig** [comment]
https://netease-cloud-api-boyce.glitch.me

**Comment by kktal** [comment]
> https://netease-cloud-api-boyce.glitch.me
朋友能给个联系方式吗，你搭在github上的这个是有效的

**Comment by BoyceLig** [comment]
> > https://netease-cloud-api-boyce.glitch.me
> > 朋友能给个联系方式吗，你搭在github上的这个是有效的

没太明白你的意思，https://t.me/Boyce_Lig

**Comment by kktal** [comment]
我在github上面新建的项目网址放到云函数里用登录会显示秘密错误，你这个可以用帮到我了

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Boyce Lig <notifications@github.com&gt;
发送时间: 2020年9月2日 16:27
收件人: ZainCheung/netease-cloud-api <netease-cloud-api@noreply.github.com&gt;
抄送: 2604836155 <2604836155@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ZainCheung/netease-cloud-api] 【活动】API接口征集 (#31)

**Comment by chenshiminliangliangan** [comment]
> [https://netease-cloud-api-boyce.glitch.me ](https://netease-cloud-api-boyce.glitch.me)

谢谢你的API

**Comment by Ruobo612** [comment]
发现问题所在了，阿里云搭建的api不行，附上一个api//直接复制作者的
https://organized-east-napkin.glitch.me

**Comment by kktal** [comment]
> 发现问题所在了，阿里云建造的api不行，附上一个api //直接复制作者的
> https://organized-east-napkin.glitch.me

作者的可以用，不过搭建在github上的访问速度很差，多账号使用有点拉胯了

**Comment by Nullwhy** [comment]
https://wy-music-api.glitch.me

**Comment by kktal** [comment]
您有尝试过自建的吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Me_x <notifications@github.com&gt;
发送时间: 2020年9月4日 23:58
收件人: ZainCheung/netease-cloud-api <netease-cloud-api@noreply.github.com&gt;
抄送: 2604836155 <2604836155@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ZainCheung/netease-cloud-api] 【活动】API接口征集 (#31)

**Comment by Nullwhy** [comment]
> 您有尝试过自建的吗？发自我的iPhone
> […](#)
> ------------------原始邮件------------------发件人：Me_x <notifications@github.com> 发送时间：2020年9月4日23:58收件人：ZainCheung / netease-cloud-api <netease-cloud-api@noreply.github.com> 抄送：2604836155 <2604836155@qq.com> ;，评论<comment@noreply.github.com> 主题：回复：[ZainCheung / netease-cloud-api]【活动】API接口征集（[＃31](https://github.com/ZainCheung/netease-cloud-api/issues/31)）

还没有

**Comment by kktal** [comment]
你api自己用着怎么样？我用你的试了一下好像有异常情况不能正常使用





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Me_x <notifications@github.com&gt;
发送时间: 2020年9月5日 00:07
收件人: ZainCheung/netease-cloud-api <netease-cloud-api@noreply.github.com&gt;
抄送: 2604836155 <2604836155@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ZainCheung/netease-cloud-api] 【活动】API接口征集 (#31)





  
您有尝试过自建的吗？发自我的iPhone
 …
 ------------------原始邮件------------------发件人：Me_x notifications@github.com 发送时间：2020年9月4日23:58收件人：ZainCheung / netease-cloud-api netease-cloud-api@noreply.github.com 抄送：2604836155 2604836155@qq.com ;，评论comment@noreply.github.com 主题：回复：[ZainCheung / netease-cloud-api]【活动】API接口征集（＃31）
  
还没有

**Comment by Nullwhy** [comment]
昨晚太晚了  我没测试   ，不行的话   我今天再搭建一个  。

**Comment by luvsicz** [comment]
https://netease.glitch.me/

**Comment by Nullwhy** [comment]
https://wy-music-x-api.glitch.me

**Comment by Becods** [comment]
https://netease-cloud-api.muir.fun

**Comment by Nullwhy** [comment]
https://wymusic-xx.glitch.me     已测试可用（接口为文档接口部署复制服务教程搭建）

**Comment by sukanka** [comment]
https://netease.sukanka.pub/ 测试可用，用 cloudflare 做了反代

**Comment by luvsicz** [comment]
[https://netease.glitch.me/](url) 因为使用的是国外的服务，调用延迟可以设置大一点。

**Comment by iwhly3** [comment]
https://api.qqlogin.com/netease/ 广州腾讯云

**Comment by ErazerQDY** [comment]
> ### 鉴于API接口的可复用性，以及方便新手试用，特开一个API征集Issue，欢迎大家积极贡献API，共同构建项目生态
> ### 规则：在下面回复你的API地址即可，一到两天内在通过测试之后即会更新发布至文档中（附带你的Github用户地址一起发布），在你回复地址时即表示已知悉并接受该规则。严禁留下带有后门的API！！！
> ### 格式要求：
> 接口地址：填写你的API地址，要求打开后可以看到欢迎界面

https://miao-neteasecloudmusicapi.glitch.me

**Comment by ErazerQDY** [comment]
https://miao-neteasecloudmusicapi.glitch.me
自测成功
（接口为文档接口部署复制服务教程搭建）

**Comment by ne-21** [comment]
https://netease.gocos.cn
北京阿里云

**Comment by a2014226393** [comment]
https://qiyou.glitch.me/

**Comment by lyalexzz** [comment]
http://www.ljfchtcc.com:4163/

**Comment by idarku** [comment]
接口地址:    http://wyy.pw/
特意注册了这个域名

**Comment by potuo** [comment]
https://musicdk-api.glitch.me/

**Comment by husky105** [comment]
> > https://netease-cloud-api-boyce.glitch.me
> > 朋友能给个联系方式吗，你搭在github上的这个是有效的

这个怎么样

**Comment by AticTI** [comment]
https://cloud-api.je6w.com/

**Comment by Catker** [comment]
https://sumrday.net/api/163music/

**Comment by aLuvletter** [comment]
https://mytools.chiser.cc/music-api/

**Comment by xy1so** [comment]
https://shijcc.top/cloudmusic-api/

**Comment by lmf020409** [comment]
怎么搭建api

**Comment by Summer-Tail** [comment]
http://lvsheng.xyz/wyy/

**Comment by WISH-WEI** [comment]
api.husky105.cn

**Comment by ShenHai9** [comment]
香港阿里云
[https://api.syhy.ink/netease-cloud/](https://api.syhy.ink/netease-cloud/)

**Comment by ShenHai9** [comment]
香港阿里云
Boce测速平均响应1.9s [https://www.boce.com/http/api.syhy.ink](https://www.boce.com/http/api.syhy.ink) 
自测功能正常 望采纳。
博客内容：[https://www.yseaer.cn/archives/191](https://www.yseaer.cn/archives/191) 
接口地址：[https://api.syhy.ink/netease-cloud/](https://api.syhy.ink/netease-cloud/)

**Comment by opsqw** [comment]
阿里云
接口地址：https://api.8610001.xyz/

**Comment by czmz** [comment]
腾讯云
接口地址 https://api.czmz.top

**Comment by 168-os** [comment]
http://apia.a919.cn

**Comment by 168-os** [comment]
接口地址:http://apia.a919.cn

**Comment by mainblog** [comment]
欢迎大家使用我的接口。平均响应时间：1.111s。
https://netease.muxiuge.com/

**Comment by WHFo** [comment]
https://wanghongfeng.cn/tool/api/netease.php  

深圳阿里云 自己测试最快0.259s 平均响应0.595s

**Comment by PengPengYoo** [comment]
https://wzp-netease-test.glitch.me

**Comment by sukanka** [comment]
> https://netease.sukanka.pub/ 测试可用，用 cloudflare 做了反代

此域名即将过期（11月26日），已经切换到 https://netease.sukanka.com/

**Comment by lyzhang0113** [comment]
http://netease.doby2333.com/

**Comment by WHFo** [comment]
[![D3NwtJ.png](https://s3.ax1x.com/2020/11/21/D3NwtJ.png)](https://imgchr.com/i/D3NwtJ)
申请删除https://wanghongfeng.cn/tool/api/netease.php
因为自从添加到列表中后，连续三天都是250错误无法登录
看你在其他issues里说的是ip被ban了，因为接口还需要自用所以申请删除。

**Comment by ZainCheung** [comment]
@WHFo 很抱歉你的API被禁，应该是被别人拿去刷取大量的账号了，在此表示很抱歉，因为这并不符合构建列表的初衷，我会重视这个问题，尽快找到新的解决方案，另外非常感谢你捐赠的API，可能已经帮到不少朋友测试项目，我会马上删掉你的接口

**Comment by ShenHai9** [comment]
> [![D3NwtJ.png](https://s3.ax1x.com/2020/11/21/D3NwtJ.png)](https://imgchr.com/i/D3NwtJ)
> 
> 申请删除https://wanghongfeng.cn/tool/api/netease.php
> 
> 因为自从添加到列表中后，连续三天都是250错误无法登录
> 
> 看你在其他issues里说的是ip被ban了，因为接口还需要自用所以申请删除。

对 我自己的api服务器ip也是被网易ban了 上次那个issues就是我提出的

最近网易应该严查 如果要出来搭建公共服务api还是建议用动态服务器的ip

现在并发一大起来 马上就会被ban

ban掉了的话我试过只有login参数的功能是用不了的
daka和sign这些直接带账号密码参数执行还是可以的

**Comment by WHFo** [comment]
@ShenHai9   麻烦删除下，上面带了我的手机号忘记打码了。

**Comment by KarewaGron** [comment]
> https://netease-cloud-api-boyce.glitch.me

感谢！

**Comment by zxc1282440990** [comment]
请问大家为啥我的密码老是错误 我都服气了 改了好几边密码还是密码错误

**Comment by PengPengYoo** [comment]
> 请问大家为啥我的密码老是错误我都服气了改了好几边密码还是密码错误

换个api试试

**Comment by qazliang** [comment]
请问，自己申请的api用来使用，是否会被加入黑名单？

**Comment by GHSshenshi** [comment]
请问现在是不能用了吗

**Comment by GHSshenshi** [comment]
> 请问现在是不能用了吗

换了个API可以用了

**Comment by vsiis** [comment]
> 请问，自己申请的api使用使用，是否会被加入黑名单？

自己用不会，频繁 大批量的才有可能被拉黑

**Comment by vsiis** [comment]
> > 请问现在是不能用了吗
> 
> 换了个API可以用了

建议自建api 比较稳定些 很简单

**Comment by bakbai** [comment]
http://api.vipvpn.vip/

**Comment by bytedo** [comment]
https://api.lalkk.com/netease-cloud-api/

**Comment by AlexWhisper** [comment]
> https://api.lalkk.com/netease-cloud-api/

非常感谢，用上了
