### ISSUE TITLE
看issues好多人遇到账号密码错误了，请教有没有解决办法了？

### ISSUE THREAD

**Issue by wy1ng** [ZainCheung/netease-cloud-api#38]
首先可保证用户名密码正确，MD532位小写Switch开关都对，因为一直用着好好的。另外API也没问题。我今天就是上传了新的code，发现多了一个国际手机号，别的也没啥操作啊，蛋疼。。。

**Comment by wy1ng** [comment]
密码改成明文也不行。。。


START RequestId: 74df4a78-08d1-48c5-95b8-baa5be6a22ed

Event RequestId: 74df4a78-08d1-48c5-95b8-baa5be6a22ed

配置文件读取完毕

Starting new HTTPS connection (1): wy1ng-netease-cloud-api.glitch.me:443

https://wy1ng-netease-cloud-api.glitch.me:443 "GET /?do=check HTTP/1.1" 200 None

api测试正常

账号: 186********  开始执行

========================================

MD5开关已打开,即将开始为你加密,密码不会上传至服务器,请知悉

Starting new HTTPS connection (1): wy1ng-netease-cloud-api.glitch.me:443

https://wy1ng-netease-cloud-api.glitch.me:443 "POST /?do=login HTTP/1.1" 200 None

2020.09.03-05:07:28   用户任务执行中断,请检查账号密码是否正确

 

END RequestId: 74df4a78-08d1-48c5-95b8-baa5be6a22ed

Report RequestId: 74df4a78-08d1-48c5-95b8-baa5be6a22ed Duration:8594ms Memory:64MB MemUsage:19.742188MB

**Comment by swvv** [comment]
一样的问题

**Comment by FightingChu** [comment]
哎呀，配了一天，各种尝试，各种改，还是提示密码错误。一样的情况。

**Comment by ye4241** [comment]
绑定邮箱用邮箱登录正常，手机号就是密码错误的。

**Comment by L-20021213** [comment]
账号密码错误是API的问题，用的人多了就这样，建议部署在服务器上自用。

**Comment by FightingChu** [comment]
emmm，我在gitme上面部署的自己的呀。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "丨浅笑安然丨"<notifications@github.com&gt;; 
发送时间: 2020年9月6日(星期天) 晚上8:53
收件人: "ZainCheung/netease-cloud-api"<netease-cloud-api@noreply.github.com&gt;; 
抄送: "梦醒回、"<774997664@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ZainCheung/netease-cloud-api] 看issues好多人遇到账号密码错误了，请教有没有解决办法了？ (#38)





 
账号密码错误是API的问题，用的人多了就这样，建议部署在服务器上自用。

**Comment by wy1ng** [comment]
> 账号密码错误是API的问题，用的人多了就这样，建议部署在服务器上自用。

我自己的API，就我自己用，哪来的用的人多。。。

**Comment by ZainCheung** [comment]
现在更新到最新的API即可解决问题，如果自己服务器上的API无法使用的话可以用glitch搭建，目前文档更新了API接口列表，如果自己搭建的API实在无法使用可以使用里面的API

**Comment by wy1ng** [comment]
已解决
