### ISSUE TITLE
自己部署服务器到腾讯云发现打开歌曲永远0首

### ISSUE THREAD

**Issue by ye4241** [ZainCheung/netease-cloud-api#41]
测试了很多次，能登录，签到永远重复，歌曲永远0首。
最后切换回了glitch，一下子就好了。
相同的代码，感觉像是IP限制导致的。

腾讯云
> 配置文件读取完毕
api测试正常
账号: ye4241@126.com  开始执行============================
登录成功
https://(此处是服务器域名)/?do=sign
{'code': 301, 'message': None}
重复签到
https://(此处是服务器域名)/?do=detail
{'level': 8, 'listenSongs': 6620, 'userPoint': {'userId': 
获取用户详情成功
https://(此处是服务器域名)/?do=daka
{'code': 200, 'count': 1000}
用户:ye4241  第1次打卡成功,即将休眠30秒
https://(此处是服务器域名)/?do=detail
{'level': 8, 'listenSongs': 6620, 'userPoint': {'userId': 
`

glitch
> 配置文件读取完毕
api测试正常
账号: ye4241@126.com  开始执行===========================
登录成功
https://netease-cloud-api-ye4241.glitch.me?do=sign
{'code': -2, 'msg': '重复签到'}
重复签到
https://netease-cloud-api-ye4241.glitch.me?do=detail
{'level': 8, 'listenSongs': 6620, 'userPoint': {'userId':
获取用户详情成功
https://netease-cloud-api-ye4241.glitch.me?do=daka
{'code': 200, 'count': 1000}
用户:ye4241  第1次打卡成功,即将休眠30秒
https://netease-cloud-api-ye4241.glitch.me?do=detail
{'level': 8, 'listenSongs': 6620, 'userPoint': {'userId':

**Comment by kktal** [comment]
哈哈你也是这个情况吗？我也是，我把api放在阿里云上，腾讯云的函数日志里显示登陆成功有执行签到和刷歌任务，但是刷歌数都0.

**Comment by ye4241** [comment]
@2604836155 看来可能是阿里和腾讯的IP都是网易的黑名单的吧

**Comment by kktal** [comment]
主要是，项目出情况之前都还是好的，是和项目一起出的状况～



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ye4241 <notifications@github.com&gt;
发送时间: 2020年9月7日 23:10
收件人: ZainCheung/netease-cloud-api <netease-cloud-api@noreply.github.com&gt;
抄送: 2604836155 <2604836155@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[ZainCheung/netease-cloud-api] 自己部署服务器到腾讯云发现打开歌曲永远0首 (#41)





 
@2604836155 看来可能是阿里和腾讯的IP都是网易的黑名单的吧

**Comment by wy1ng** [comment]
我一直提示任务中断，可是什么配置都是正常的，已经运行2个月了，前些天突然就不行了，这两周我试了N次都不行。。。

**Comment by ZainCheung** [comment]
> 我一直提示任务中断，可是什么配置都是正常的，已经运行2个月了，前些天突然就不行了，这两周我试了N次都不行。。。

很大概率是API导致的，如果无法确保API没有问题的话，可以试一下文档提供的几个API：
https://zaincheung.github.io/netease-cloud/#/demo/

**Comment by xiaowangzi2020** [comment]
同样

**Comment by wy1ng** [comment]
> 同样

把整个项目删除，重新部署。我之前是在原项目上删删改改，不知道哪里就出问题了，重新部署一遍OK了。

**Comment by xydche** [comment]
我也是自建API怎么都不行，用demo里的没问题。
