### ISSUE TITLE
网易云打卡 提示api测试失败

### ISSUE THREAD

**Issue by best11589835** [ZainCheung/netease-cloud-api#5]

**Comment by ZainCheung** [comment]
因为我的API用的人多了，，有时候就会挂掉，，建议看看API部署的第二种方法，花费两分钟搭建一个自己的API

**Comment by best11589835** [comment]
> 因为我的API用的人多了，，有时候就会挂掉，，建议看看API部署的第二种方法，花两分钟建造一个自己的API

好的  谢谢
