### ISSUE TITLE
API异常

### ISSUE THREAD

**Issue by shi7087874** [ZainCheung/netease-cloud-api#6]
Starting new HTTPS connection (1): netease-cloud-api.glitch.me:443

https://netease-cloud-api.glitch.me:443 "GET /?do=check HTTP/1.1" 503 180

api测试异常

**Comment by ZainCheung** [comment]
因为我的API用的人多了，，有时候就会挂掉，，建议看看API部署的第二种方法，花费两分钟搭建一个自己的API
