### ISSUE TITLE
测试时出现异常

### ISSUE THREAD

**Issue by oishi81** [ZainCheung/netease-cloud-api#9]
Starting new HTTPS connection (1): netease-cloud-api.glitch.me:443

https://netease-cloud-api.glitch.me:443 "GET /?do=check HTTP/1.1" 503 180

api测试异常

**Comment by ZainCheung** [comment]
因为我的API用的人多了，，有时候就会挂掉，，建议看看API部署的第二种方法，花费两分钟搭建一个自己的API

**Comment by lovecn** [comment]
@ZainCheung 我自己建了api，但腾讯云函数里运行一直提示 用户任务执行中断,请检查账号密码是否正确 ，我确认账号和md5都没错。

**Comment by ZainCheung** [comment]
> @ZainCheung 我自己建了api，但腾讯云函数里运行一直提示 用户任务执行中断,请检查账号密码是否正确 ，我确认账号和md5都没错。

自己搭建完API有没有更改配置文件里的API地址，如果没有需要改过来，如果不起作用可以复制日志或者截图日志发过来
